// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitEmE7Wzj5bgzVQrwQPe2pSjbZeebUgk',
    appId: '1:735846647282:web:321a81e92b290520f1176b',
    messagingSenderId: '735846647282',
    projectId: 'fashion-store-f1d1f',
    authDomain: 'fashion-store-f1d1f.firebaseapp.com',
    storageBucket: 'fashion-store-f1d1f.appspot.com',
    measurementId: 'G-W26SG6LMJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHifWsovV-u4HVveiZ2AjstE9mazN8fk',
    appId: '1:735846647282:android:7bb5f54825fd1f03f1176b',
    messagingSenderId: '735846647282',
    projectId: 'fashion-store-f1d1f',
    storageBucket: 'fashion-store-f1d1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgyU_E0d-jSwIBBujf5sLPOAp6yLqsK34',
    appId: '1:735846647282:ios:05c4c43f7eba58eef1176b',
    messagingSenderId: '735846647282',
    projectId: 'fashion-store-f1d1f',
    storageBucket: 'fashion-store-f1d1f.appspot.com',
    iosClientId: '735846647282-jq3scshrlecekgdkvvi0irf0ugemng7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionStore',
  );
}
